import { useEffect, useMemo, useRef, useState } from 'react';
import { SynthEngine } from './audio/SynthEngine';
import { createPattern, STEPS } from './audio/sequencer';
import { DEFAULT_PATCH, type Patch, type Step, type Waveform } from './audio/types';
import { midiBlob, midiPattern, mp3Blob, renderProject, wavBlob } from './audio/exporters';

type Page = 'studio' | 'library' | 'learn';
type LibraryPatch = Patch & { category: string; description: string };

const presetLibrary: LibraryPatch[] = [
  { ...DEFAULT_PATCH, category: 'Analog', description: 'A clean, flexible starting point.' },
  { ...DEFAULT_PATCH, id: 'pad', name: 'Warm Pad', waveform: 'triangle', cutoff: 850, attack: .35, release: 1.1, category: 'Atmosphere', description: 'Slow, soft and spacious.' },
  { ...DEFAULT_PATCH, id: 'bass', name: 'Deep Bass', waveform: 'square', cutoff: 420, resonance: 5, release: .15, category: 'Bass', description: 'Short and weighty for a groove.' },
  { ...DEFAULT_PATCH, id: 'glow', name: 'Neon Glow', waveform: 'sine', cutoff: 3600, resonance: .8, attack: .08, release: .65, category: 'Lead', description: 'A smooth lead that cuts through.' },
  { ...DEFAULT_PATCH, id: 'pluck', name: 'Glass Pluck', waveform: 'triangle', cutoff: 5200, resonance: 7, attack: .006, release: .18, category: 'Keys', description: 'Bright, fast, and percussive.' },
  { ...DEFAULT_PATCH, id: 'noir', name: 'Noir Pulse', waveform: 'sawtooth', cutoff: 980, resonance: 9, attack: .015, release: .34, category: 'Bass', description: 'A filtered pulse for darker tracks.' },
];
const keys = [60, 62, 64, 65, 67, 69, 71, 72];
const emptyPattern = () => Array.from({ length: STEPS }, () => ({ active: false, note: 60, velocity: .8 }));
const startPattern = () => Array.from({ length: STEPS }, (_, i) => [0, 4, 8, 12].includes(i));
const hatPattern = () => Array.from({ length: STEPS }, (_, i) => i % 2 === 0);
const patternPacks = [
  { id: 'starter', name: 'Starter', melody: [0, 4, 8, 12], notes: [60, 60, 64, 67], kick: [0, 4, 8, 12], hat: [0, 2, 4, 6, 8, 10, 12, 14] },
  { id: 'house', name: 'House', melody: [0, 3, 6, 8, 11, 14], notes: [60, 64, 67, 60, 65, 69], kick: [0, 4, 8, 12], hat: [2, 6, 10, 14] },
  { id: 'acid', name: 'Acid', melody: [0, 2, 3, 5, 7, 8, 10, 11, 13, 15], notes: [48, 55, 60, 55, 62, 60, 55, 48, 55, 60], kick: [0, 3, 6, 8, 11, 14], hat: [1, 2, 5, 6, 9, 10, 13, 14] },
  { id: 'ambient', name: 'Ambient', melody: [0, 6, 10], notes: [60, 64, 67], kick: [0, 8], hat: [4, 12] },
];
const fromPack = (indices: number[], notes: number[] = []) => Array.from({ length: STEPS }, (_, i) => ({ active: indices.includes(i), note: notes[indices.indexOf(i)] ?? 60, velocity: .72 }));
const booleanPack = (indices: number[]) => Array.from({ length: STEPS }, (_, i) => indices.includes(i));

export function App() {
  const engine = useMemo(() => new SynthEngine(), []);
  const [page, setPage] = useState<Page>('studio');
  const [patch, setPatch] = useState<Patch>(DEFAULT_PATCH);
  const [pattern, setPattern] = useState<Step[]>(createPattern);
  const [drums, setDrums] = useState<boolean[]>(startPattern);
  const [hats, setHats] = useState<boolean[]>(hatPattern);
  const [snares, setSnares] = useState<boolean[]>(() => booleanPack([4, 12]));
  const [playing, setPlaying] = useState(false), [tempo, setTempo] = useState(112), [step, setStep] = useState(-1);
  const [volume, setVolume] = useState(70), [delay, setDelay] = useState(8);
  const [metronome, setMetronome] = useState(false), [keyboardOctave, setKeyboardOctave] = useState(4);
  const [synthGain, setSynthGain] = useState(90), [drumGain, setDrumGain] = useState(90), [selectedStep, setSelectedStep] = useState(0);
  const [arpEnabled, setArpEnabled] = useState(false), [recording, setRecording] = useState(false), [sampleName, setSampleName] = useState('No sample loaded');
  const [micRecording, setMicRecording] = useState(false), [looping, setLooping] = useState(false);
  const [favorites, setFavorites] = useState<string[]>(() => JSON.parse(localStorage.getItem('omnisynth-favorites') ?? '[]'));
  const [customPresets, setCustomPresets] = useState<LibraryPatch[]>(() => JSON.parse(localStorage.getItem('omnisynth-custom-presets') ?? '[]'));
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  const [versions, setVersions] = useState<Array<{ at: string; name: string }>>([]);
  const [prompt, setPrompt] = useState('Velvet analog pad with a soft attack');
  const [notice, setNotice] = useState('Ready to play');
  const [projectName, setProjectName] = useState('Midnight Drive');
  const timer = useRef<number | undefined>(undefined);
  const tapTimes = useRef<number[]>([]);
  const lastPattern = useRef<Step[] | undefined>(undefined), replayingHistory = useRef(false);
  const [undoStack, setUndoStack] = useState<Step[][]>([]), [redoStack, setRedoStack] = useState<Step[][]>([]);
  const recorder = useRef<MediaRecorder | undefined>(undefined);
  const recordedParts = useRef<BlobPart[]>([]);
  const micRecorder = useRef<MediaRecorder | undefined>(undefined), micParts = useRef<BlobPart[]>([]), micStream = useRef<MediaStream | undefined>(undefined), loopTimer = useRef<number | undefined>(undefined);
  const collab = useRef<BroadcastChannel | undefined>(undefined);

  useEffect(() => { const sync = () => { const value = location.hash.slice(1); setPage(value === 'library' || value === 'learn' ? value : 'studio'); }; sync(); addEventListener('hashchange', sync); return () => removeEventListener('hashchange', sync); }, []);
  useEffect(() => { const raw = localStorage.getItem('omnisynth-project'); if (!raw) return; try { const saved = JSON.parse(raw); if (saved.patch) setPatch({ ...DEFAULT_PATCH, ...saved.patch }); if (saved.pattern) setPattern(saved.pattern); if (saved.drums) setDrums(saved.drums); if (saved.hats) setHats(saved.hats); if (saved.snares) setSnares(saved.snares); if (saved.tempo) setTempo(saved.tempo); if (saved.volume) setVolume(saved.volume); if (saved.delay) setDelay(saved.delay); if (saved.synthGain) setSynthGain(saved.synthGain); if (saved.drumGain) setDrumGain(saved.drumGain); if (saved.metronome) setMetronome(saved.metronome); if (saved.keyboardOctave) setKeyboardOctave(saved.keyboardOctave); if (saved.projectName) setProjectName(saved.projectName); if (saved.theme) setTheme(saved.theme); if (saved.versions) setVersions(saved.versions); setNotice('Restored your last local session'); } catch { localStorage.removeItem('omnisynth-project'); } }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { if (!lastPattern.current) { lastPattern.current = pattern.map(item => ({ ...item })); return; } if (replayingHistory.current) { replayingHistory.current = false; lastPattern.current = pattern.map(item => ({ ...item })); return; } setUndoStack(items => [...items, lastPattern.current!.map(item => ({ ...item }))].slice(-32)); setRedoStack([]); lastPattern.current = pattern.map(item => ({ ...item })); }, [pattern]);
  useEffect(() => { const id = window.setTimeout(() => { localStorage.setItem('omnisynth-project', JSON.stringify({ patch, pattern, drums, hats, snares, volume, delay, synthGain, drumGain, metronome, keyboardOctave, tempo, projectName, theme, versions })); }, 800); return () => clearTimeout(id); }, [patch, pattern, drums, hats, snares, volume, delay, synthGain, drumGain, metronome, keyboardOctave, tempo, projectName, theme, versions]);
  useEffect(() => { collab.current = new BroadcastChannel('omnisynth-local-room'); collab.current.onmessage = event => { const shared = event.data; if (shared?.type !== 'project') return; if (shared.patch) setPatch({ ...DEFAULT_PATCH, ...shared.patch }); if (shared.pattern) setPattern(shared.pattern); if (shared.drums) setDrums(shared.drums); if (shared.hats) setHats(shared.hats); if (shared.snares) setSnares(shared.snares); if (shared.tempo) setTempo(shared.tempo); setNotice('Live project update received from a local room'); }; return () => collab.current?.close(); }, []);
  useEffect(() => () => { clearInterval(timer.current); clearInterval(loopTimer.current); engine.allNotesOff(patch); }, [engine, patch]);
  const navigate = (next: Page) => { location.hash = next; setPage(next); scrollTo({ top: 0, behavior: 'smooth' }); };
  const play = async () => { await engine.start(); engine.setMasterGain(volume / 100); engine.setSynthGain(synthGain / 100); engine.setDrumGain(drumGain / 100); engine.setDelay(delay / 100); if (playing) { clearInterval(timer.current); setPlaying(false); setStep(-1); engine.allNotesOff(patch); return; } setPlaying(true); let next = -1; timer.current = window.setInterval(() => { next = (next + 1) % STEPS; setStep(next); const cell = pattern[next]; if (drums[next]) engine.kick(); if (snares[next]) engine.snare(); if (hats[next] || (metronome && next % 4 === 0)) engine.hat(); if (cell.active) { engine.noteOn(cell.note, patch, cell.velocity); setTimeout(() => engine.noteOff(cell.note, patch), (60000 / tempo) * .22); } }, 60000 / tempo / 4); };
  const update = <K extends keyof Patch>(key: K, value: Patch[K]) => setPatch(current => ({ ...current, [key]: value }));
  const loadPreset = (next: Patch) => { setPatch(next); setNotice(`${next.name} loaded into the synth`); };
  const save = () => { const nextVersions = [{ at: new Date().toLocaleTimeString(), name: projectName }, ...versions].slice(0, 12); setVersions(nextVersions); localStorage.setItem('omnisynth-project', JSON.stringify({ patch, pattern, drums, hats, snares, volume, delay, synthGain, drumGain, metronome, keyboardOctave, tempo, projectName, theme, versions: nextVersions })); setNotice('Project saved with a local version checkpoint'); };
  const download = () => { const blob = new Blob([JSON.stringify({ version: 3, name: projectName, patch, pattern, drums, hats, snares, volume, delay, synthGain, drumGain, metronome, keyboardOctave, tempo }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${projectName.replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'omnisynth-project'}.omnisynth.json`; link.click(); URL.revokeObjectURL(link.href); setNotice('Project file downloaded'); };
  const generate = () => { const words = prompt.toLowerCase(); const next: Patch = words.includes('bass') ? presetLibrary[2] : words.includes('pad') || words.includes('warm') || words.includes('velvet') ? presetLibrary[1] : words.includes('pluck') ? presetLibrary[4] : { ...DEFAULT_PATCH, id: 'generated', name: 'Generated Lead', waveform: words.includes('soft') ? 'sine' : 'sawtooth', cutoff: words.includes('bright') ? 4200 : 1500 }; loadPreset(next); };
  const randomize = () => { setPattern(Array.from({ length: STEPS }, (_, i) => ({ active: Math.random() > .48, note: [48, 55, 60, 64, 67][i % 5], velocity: .55 + Math.random() * .4 }))); setDrums(Array.from({ length: STEPS }, (_, i) => i % 4 === 0 || Math.random() > .8)); setSnares(Array.from({ length: STEPS }, (_, i) => i % 8 === 4 || Math.random() > .92)); setHats(Array.from({ length: STEPS }, () => Math.random() > .45)); setNotice('New pattern generated'); };
  const clear = () => { setPattern(emptyPattern()); setDrums(Array.from({ length: STEPS }, () => false)); setSnares(Array.from({ length: STEPS }, () => false)); setHats(Array.from({ length: STEPS }, () => false)); setNotice('Pattern cleared'); };
  const applyPack = (packId: string) => { const pack = patternPacks.find(item => item.id === packId) ?? patternPacks[0]; setPattern(fromPack(pack.melody, pack.notes)); setDrums(booleanPack(pack.kick)); setSnares(booleanPack([4, 12])); setHats(booleanPack(pack.hat)); setNotice(`${pack.name} pattern loaded`); };
  const undo = () => { const previous = undoStack.at(-1); if (!previous) { setNotice('Nothing to undo'); return; } replayingHistory.current = true; setRedoStack(items => [...items, pattern.map(item => ({ ...item }))]); setUndoStack(items => items.slice(0, -1)); setPattern(previous.map(item => ({ ...item }))); setNotice('Pattern edit undone'); };
  const redo = () => { const next = redoStack.at(-1); if (!next) { setNotice('Nothing to redo'); return; } replayingHistory.current = true; setUndoStack(items => [...items, pattern.map(item => ({ ...item }))]); setRedoStack(items => items.slice(0, -1)); setPattern(next.map(item => ({ ...item }))); setNotice('Pattern edit redone'); };
  const tapTempo = () => { const now = performance.now(); tapTimes.current = [...tapTimes.current.filter(time => now - time < 2400), now]; if (tapTimes.current.length > 1) { const gaps = tapTimes.current.slice(1).map((time, i) => time - tapTimes.current[i]); const bpm = Math.round(60000 / (gaps.reduce((sum, gap) => sum + gap, 0) / gaps.length)); if (bpm >= 40 && bpm <= 240) { setTempo(bpm); setNotice(`Tempo set to ${bpm} BPM`); } } };
  const transpose = (amount: number) => { setPattern(items => items.map(item => ({ ...item, note: Math.max(24, Math.min(96, item.note + amount)) }))); setNotice(`Melody shifted ${amount > 0 ? 'up' : 'down'} one octave`); };
  const playChord = async (root: number, name: string) => { await engine.start(); engine.setMasterGain(volume / 100); engine.setDelay(delay / 100); const notes = [root, root + 4, root + 7]; if (arpEnabled) { notes.forEach((note, index) => setTimeout(() => { engine.noteOn(note, patch, .7); setTimeout(() => engine.noteOff(note, patch), 260); }, index * 145)); } else { notes.forEach(note => engine.noteOn(note, patch, .7)); setTimeout(() => notes.forEach(note => engine.noteOff(note, patch)), Math.max(360, patch.release * 1000 + 300)); } setNotice(`${name} major ${arpEnabled ? 'arpeggio' : 'chord'} played`); };
  const downloadBlob = (blob: Blob, filename: string) => { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
  const exportAudio = (format: 'wav' | 'mp3' | 'midi') => { if (format === 'midi') { downloadBlob(midiBlob(pattern, tempo), `${projectName}.mid`); setNotice('MIDI file exported'); return; } const samples = renderProject({ patch, pattern, kicks: drums, hats, snares, tempo }); downloadBlob(format === 'wav' ? wavBlob(samples) : mp3Blob(samples), `${projectName}.${format}`); setNotice(`${format.toUpperCase()} mix exported locally`); };
  const importMidi = async (file: File) => { try { setPattern(await midiPattern(file)); setNotice(`${file.name} imported into the melody lane`); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not import MIDI'); } };
  const importSample = async (file: File) => { try { await engine.loadSample(file); setSampleName(file.name); setNotice(`${file.name} loaded into the sampler`); } catch { setNotice('This audio file could not be decoded in your browser'); } };
  const toggleRecording = async () => { if (recording) { recorder.current?.stop(); return; } try { await engine.start(); const stream = engine.getRecordingStream(); if (!stream || !window.MediaRecorder) throw new Error(); recordedParts.current = []; const next = new MediaRecorder(stream); recorder.current = next; next.ondataavailable = event => { if (event.data.size) recordedParts.current.push(event.data); }; next.onstop = async () => { setRecording(false); const file = new File([new Blob(recordedParts.current, { type: next.mimeType || 'audio/webm' })], 'omnisynth-recording.webm', { type: next.mimeType || 'audio/webm' }); await importSample(file); setNotice('Performance recorded and loaded as a sampler sound'); }; next.start(); setRecording(true); setNotice('Recording the studio output… press stop when ready'); } catch { setNotice('Recording is not supported by this browser'); } };
  const toggleMicRecording = async () => { if (micRecording) { micRecorder.current?.stop(); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); micStream.current = stream; micParts.current = []; const next = new MediaRecorder(stream); micRecorder.current = next; next.ondataavailable = event => { if (event.data.size) micParts.current.push(event.data); }; next.onstop = async () => { setMicRecording(false); micStream.current?.getTracks().forEach(track => track.stop()); const file = new File([new Blob(micParts.current, { type: next.mimeType || 'audio/webm' })], 'mic-sample.webm', { type: next.mimeType || 'audio/webm' }); await importSample(file); setNotice('Microphone sample loaded into the sampler'); }; next.start(); setMicRecording(true); setNotice('Recording microphone… press stop when ready'); } catch { setNotice('Microphone permission was not granted or recording is unavailable'); } };
  const toggleLoop = () => { if (looping) { clearInterval(loopTimer.current); setLooping(false); setNotice('Sampler loop stopped'); return; } if (!engine.hasSample()) { setNotice('Load or record a sample before starting the looper'); return; } engine.triggerSample(); loopTimer.current = window.setInterval(() => engine.triggerSample(), Math.round(60 / tempo * 4 * 4 * 1000)); setLooping(true); setNotice('Sampler looping every 4 bars'); };
  const enableMidi = async () => { try { const access = await navigator.requestMIDIAccess(); access.inputs.forEach(input => { input.onmidimessage = event => { if (!event.data || event.data.length < 3) return; const [status, note, velocity] = event.data; const type = status & 0xf0; if (type === 0x90 && velocity > 0) { engine.start().then(() => engine.noteOn(note, patch, velocity / 127)); } if (type === 0x80 || (type === 0x90 && velocity === 0)) engine.noteOff(note, patch); }; }); setNotice(`${access.inputs.size} MIDI input${access.inputs.size === 1 ? '' : 's'} connected`); } catch { setNotice('MIDI access was not available or was declined'); } };
  const saveCustomPreset = () => { const next: LibraryPatch = { ...patch, id: `custom-${Date.now()}`, name: `${patch.name} Copy`, category: 'Custom', description: 'A locally saved custom patch.' }; const items = [next, ...customPresets].slice(0, 24); setCustomPresets(items); localStorage.setItem('omnisynth-custom-presets', JSON.stringify(items)); setNotice('Custom preset saved locally'); };
  const toggleFavorite = (id: string) => { const items = favorites.includes(id) ? favorites.filter(item => item !== id) : [...favorites, id]; setFavorites(items); localStorage.setItem('omnisynth-favorites', JSON.stringify(items)); };
  const shareLocal = async () => { const shared = { type: 'project', patch, pattern, drums, hats, snares, tempo }; collab.current?.postMessage(shared); const payload = btoa(unescape(encodeURIComponent(JSON.stringify(shared)))); try { await navigator.clipboard.writeText(`${location.origin}${location.pathname}#project=${payload}`); setNotice('Project link copied — local-room peers also received the update'); } catch { setNotice('Local-room peers received the project update'); } };
  useEffect(() => { const pressed = new Set<string>(); const keyMap: Record<string, number> = { a: 0, w: 1, s: 2, e: 3, d: 4, f: 5, t: 6, g: 7, y: 8, h: 9, u: 10, j: 11, k: 12 }; const isTyping = (target: EventTarget | null) => target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement; const down = async (event: KeyboardEvent) => { if (isTyping(event.target) || pressed.has(event.key.toLowerCase())) return; const key = event.key.toLowerCase(); if (key === ' ') { event.preventDefault(); play(); return; } if (key === 'z' || key === 'x') { setKeyboardOctave(current => { const next = Math.max(2, Math.min(6, current + (key === 'x' ? 1 : -1))); setNotice(`Keyboard octave ${next}`); return next; }); return; } if (!(key in keyMap)) return; pressed.add(key); const note = keyboardOctave * 12 + keyMap[key]; await engine.start(); engine.setMasterGain(volume / 100); engine.setDelay(delay / 100); engine.noteOn(note, patch); }; const up = (event: KeyboardEvent) => { const key = event.key.toLowerCase(); if (!(key in keyMap)) return; pressed.delete(key); engine.noteOff(keyboardOctave * 12 + keyMap[key], patch); }; addEventListener('keydown', down); addEventListener('keyup', up); return () => { removeEventListener('keydown', down); removeEventListener('keyup', up); }; }, [engine, patch, volume, delay, keyboardOctave, play]);
  const beginLesson = (preset: Patch, lesson: string) => { loadPreset(preset); navigate('studio'); setNotice(`${lesson}: preset loaded — follow the lesson steps`); };

  const studioProps = { projectName, setProjectName, playing, play, tempo, setTempo, volume, setVolume, delay, setDelay, metronome, setMetronome, keyboardOctave, engine, patch, update, pattern, setPattern, drums, setDrums, hats, setHats, snares, setSnares, step, prompt, setPrompt, generate, loadPreset, randomize, clear, save, download, navigate, applyPack, tapTempo, transpose, playChord, synthGain, setSynthGain, drumGain, setDrumGain, selectedStep, setSelectedStep, arpEnabled, setArpEnabled, recording, toggleRecording, micRecording, toggleMicRecording, looping, toggleLoop, sampleName, importSample, importMidi, exportAudio, enableMidi, saveCustomPreset, favorites, toggleFavorite, customPresets, versions, theme, setTheme, shareLocal, undo, redo };
  return <main><Header page={page} notice={notice} navigate={navigate} onSave={save}/>{page === 'studio' && <><Studio {...studioProps}/><StudioDeck {...studioProps}/></>} {page === 'library' && <Library presets={[...presetLibrary, ...customPresets]} loadPreset={loadPreset} navigate={navigate} favorites={favorites} toggleFavorite={toggleFavorite}/>} {page === 'learn' && <Learn beginLesson={beginLesson} navigate={navigate}/>}</main>;
}

function Header({ page, notice, navigate, onSave }: { page: Page; notice: string; navigate: (page: Page) => void; onSave: () => void }) { return <header><div className="brand">◈ OmniSynth <em>STUDIO</em></div><nav>{(['studio', 'library', 'learn'] as Page[]).map(item => <button className={page === item ? 'nav-active' : ''} onClick={() => navigate(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav><div className="status">● {notice}</div><button onClick={onSave}>Save project</button></header>; }

function Studio(props: any) {
  const { projectName, setProjectName, playing, play, tempo, setTempo, volume, setVolume, delay, setDelay, metronome, setMetronome, keyboardOctave, engine, patch, update, pattern, setPattern, drums, setDrums, hats, setHats, snares, setSnares, step, prompt, setPrompt, generate, loadPreset, randomize, clear, save, download, navigate, applyPack, tapTempo, transpose, playChord, synthGain, setSynthGain, drumGain, setDrumGain, selectedStep, setSelectedStep, arpEnabled, setArpEnabled, recording, toggleRecording, sampleName, importSample, importMidi, exportAudio, enableMidi, saveCustomPreset, favorites, toggleFavorite, customPresets, versions, theme, setTheme, shareLocal } = props;
  return <><section className="hero"><div><p className="eyebrow">YOUR BROWSER-BASED MUSIC STUDIO</p><h1>Make something<br/><i>you’ve never heard.</i></h1><p>Design a sound, create a groove, and export the project. Everything in this studio runs locally in your browser.</p><div className="hero-actions"><button className="play" onClick={play}>{playing ? '■ Stop session' : '▶ Start making sound'}</button><button className="ghost" onClick={download}>⇩ Export project</button></div></div><div className="prompt"><label>SMART PATCH MAKER <span>LIVE</span></label><textarea value={prompt} onChange={e => setPrompt(e.target.value)} aria-label="Describe a sound"/><button onClick={generate}>Create patch →</button><small>Try “deep bass”, “warm pad”, “glass pluck”, or “soft sine”.</small></div></section>
  <section className="workspace"><aside><p>PROJECT</p><input className="project-name" value={projectName} onChange={e => setProjectName(e.target.value)} aria-label="Project name"/><button className={playing ? 'stop' : 'play'} onClick={play}>{playing ? '■ Stop transport' : '▶ Play pattern'}</button><label className="tempo">Tempo <input type="number" min="40" max="240" value={tempo} onChange={e => setTempo(+e.target.value)} /> BPM</label><div className="transport-tools"><button onClick={tapTempo}>TAP</button><label><input type="checkbox" checked={metronome} onChange={e => setMetronome(e.target.checked)}/> Metronome</label></div><p className="mixer-title">MIXER</p><label className="mixer">MASTER <b>{volume}%</b><input aria-label="Master volume" type="range" min="0" max="100" value={volume} onChange={e => { const value = +e.target.value; setVolume(value); engine.setMasterGain(value / 100); }}/></label><label className="mixer">ECHO <b>{delay}%</b><input aria-label="Echo amount" type="range" min="0" max="45" value={delay} onChange={e => { const value = +e.target.value; setDelay(value); engine.setDelay(value / 100); }}/></label><hr/><p>PATCH LIBRARY</p>{presetLibrary.slice(0, 4).map(item => <button className={patch.id === item.id ? 'preset active' : 'preset'} onClick={() => loadPreset(item)} key={item.id}>{item.name}</button>)}<button className="preset library-link" onClick={() => navigate('library')}>Browse all patches →</button><hr/><p>PATTERN BANK</p><div className="pack-grid">{patternPacks.map(pack => <button className="preset" onClick={() => applyPack(pack.id)} key={pack.id}>{pack.name}</button>)}</div><button className="preset" onClick={randomize}>✦ Generate variation</button><button className="preset" onClick={clear}>⌫ Clear pattern</button><div className="transpose-tools"><button onClick={() => transpose(-12)}>− OCT</button><button onClick={() => transpose(12)}>+ OCT</button></div><hr/><p>ACTIONS</p><button className="preset" onClick={save}>Save locally</button><button className="preset" onClick={download}>Download project</button></aside>
  <div className="rack"><div className="module-title"><span>SYNTH / SUBTRACTIVE</span><b>{patch.name}</b></div><div className="controls controls-wide"><Control label="Waveform"><select value={patch.waveform} onChange={e => update('waveform', e.target.value as Waveform)}>{['sine','sawtooth','square','triangle'].map(item => <option key={item}>{item}</option>)}</select></Control><Knob label="Cutoff" value={patch.cutoff} min={120} max={8000} suffix=" Hz" set={(v: number) => update('cutoff', v)}/><Knob label="Resonance" value={patch.resonance} min={.1} max={18} step={.1} set={(v: number) => update('resonance', v)}/><Knob label="Detune" value={patch.detune} min={0} max={35} suffix=" ct" set={(v: number) => update('detune', v)}/><Knob label="Drive" value={patch.drive} min={0} max={1} step={.05} set={(v: number) => update('drive', v)}/><Knob label="Attack" value={patch.attack} min={.005} max={1} step={.005} suffix=" s" set={(v: number) => update('attack', v)}/><Knob label="Release" value={patch.release} min={.02} max={2} step={.01} suffix=" s" set={(v: number) => update('release', v)}/></div><Oscilloscope engine={engine} active={playing}/><div className="instrument-topline"><span>PLAY LIVE · OCTAVE {keyboardOctave}</span><span>A–K keys · Z / X shifts octave · Space starts transport</span></div><div className="keyboard">{keys.map((note, i) => <button key={note} onPointerDown={async () => { await engine.start(); engine.setMasterGain(volume / 100); engine.setDelay(delay / 100); engine.noteOn(note, patch); }} onPointerUp={() => engine.noteOff(note, patch)} onPointerLeave={() => engine.noteOff(note, patch)}>{['C','D','E','F','G','A','B','C'][i]}<small>{note}</small></button>)}</div><div className="performance"><div><span>CHORD PADS</span><small>Click to audition</small></div>{[{ root: 60, name: 'C' }, { root: 62, name: 'D' }, { root: 65, name: 'F' }, { root: 67, name: 'G' }].map(chord => <button onClick={() => playChord(chord.root, chord.name)} key={chord.name}>{chord.name}<small>major</small></button>)}</div><Sequencer title="MELODIC SEQUENCER" cells={pattern.map((item: Step) => item.active)} step={step} toggle={(i: number) => setPattern((items: Step[]) => items.map((item, index) => index === i ? { ...item, active: !item.active } : item))}/><Sequencer title="KICK" cells={drums} step={step} kind="kick" toggle={(i: number) => setDrums((items: boolean[]) => items.map((item, index) => index === i ? !item : item))}/><Sequencer title="HI-HAT" cells={hats} step={step} kind="hat" toggle={(i: number) => setHats((items: boolean[]) => items.map((item, index) => index === i ? !item : item))}/></div></section><footer>LOCAL-FIRST STUDIO · Double oscillator synth, live oscilloscope, drive, delay, chord pads, kick + hi-hat drum machine, pattern bank, keyboard shortcuts, save and export.</footer></>;
}

function Sequencer({ title, cells, step, toggle, kind = 'on' }: { title: string; cells: boolean[]; step: number; toggle: (i: number) => void; kind?: string }) { return <><div className="module-title drum-head"><span>{title}</span><b>CLICK CELLS TO EDIT</b></div><div className={`sequencer ${kind === 'kick' ? 'drum-sequencer' : ''}`}>{cells.map((active, i) => <button onClick={() => toggle(i)} key={i} className={`${active ? kind : ''} ${step === i ? 'current' : ''}`}><small>{i + 1}</small><strong>{active ? '●' : '·'}</strong></button>)}</div></>; }
function Control({ label, children }: { label: string; children: React.ReactNode }) { return <label className="control"><span>{label}</span>{children}</label>; }
function Knob({ label, value, min, max, step = 1, suffix = '', set }: { label: string; value: number; min: number; max: number; step?: number; suffix?: string; set: (value: number) => void }) { return <label className="knob"><span>{label}</span><input type="range" value={value} min={min} max={max} step={step} onChange={e => set(+e.target.value)}/><b>{value}{suffix}</b></label>; }

function StudioDeck(props: any) {
  const { engine, patch, update, pattern, setPattern, tempo, synthGain, setSynthGain, drumGain, setDrumGain, selectedStep, setSelectedStep, arpEnabled, setArpEnabled, recording, toggleRecording, micRecording, toggleMicRecording, looping, toggleLoop, sampleName, importSample, importMidi, exportAudio, enableMidi, saveCustomPreset, favorites, toggleFavorite, customPresets, versions, theme, setTheme, shareLocal, undo, redo } = props;
  const [tab, setTab] = useState<'compose' | 'sound' | 'files' | 'project'>('compose');
  const [root, setRoot] = useState(60), [scale, setScale] = useState<'major' | 'minor' | 'pentatonic'>('minor');
  const scales = { major: [0, 2, 4, 5, 7, 9, 11], minor: [0, 2, 3, 5, 7, 8, 10], pentatonic: [0, 3, 5, 7, 10] };
  const selected = pattern[selectedStep] ?? pattern[0];
  const updateStep = (next: Partial<Step>) => setPattern((items: Step[]) => items.map((item, index) => index === selectedStep ? { ...item, ...next } : item));
  const makeMelody = () => { const notes = scales[scale].map(interval => root + interval); setPattern((items: Step[]) => items.map((item, index) => ({ ...item, active: index % 2 === 0 || Math.random() > .62, note: notes[(index * 2 + (index > 7 ? 2 : 0)) % notes.length], velocity: .55 + (index % 3) * .13 }))); };
  const addChordProgression = () => { const degree = scale === 'minor' ? [0, 5, 3, 4] : [0, 4, 5, 3]; const scaleNotes = scales[scale]; setPattern((items: Step[]) => items.map((item, index) => { const chordRoot = root + scaleNotes[degree[Math.floor(index / 4)]]; return { ...item, active: index % 4 === 0, note: chordRoot, velocity: .8 }; })); };
  const sampleInput = useRef<HTMLInputElement | null>(null), midiInput = useRef<HTMLInputElement | null>(null);
  return <section className="studio-deck"><div className="deck-title"><div><p>EXPANDED STUDIO TOOLS</p><h2>Compose, shape, export.</h2></div><div className="deck-tabs" role="tablist" aria-label="Studio tool categories">{(['compose','sound','files','project'] as const).map(item => <button role="tab" aria-selected={tab === item} className={tab === item ? 'deck-active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div></div>
    {tab === 'compose' && <div className="deck-grid compose-grid"><article className="tool-panel"><span>STEP EDITOR</span><h3>Note and velocity</h3><div className="step-picker">{pattern.map((item: Step, index: number) => <button className={selectedStep === index ? 'selected-step' : item.active ? 'active-step' : ''} onClick={() => setSelectedStep(index)} key={index}>{index + 1}</button>)}</div><label>Note <input aria-label="Selected step note" type="number" min="24" max="96" value={selected.note} onChange={event => updateStep({ note: +event.target.value })}/></label><label>Velocity <input aria-label="Selected step velocity" type="range" min=".1" max="1" step=".05" value={selected.velocity} onChange={event => updateStep({ velocity: +event.target.value })}/><b>{Math.round(selected.velocity * 100)}%</b></label><div className="dual-actions"><button onClick={undo}>↶ Undo</button><button onClick={redo}>↷ Redo</button></div><button onClick={() => updateStep({ active: !selected.active })}>{selected.active ? 'Mute step' : 'Enable step'}</button></article><article className="tool-panel"><span>HARMONY + MELODY</span><h3>Scale-aware writing</h3><div className="field-pair"><label>Key <select value={root} onChange={event => setRoot(+event.target.value)}>{[['C',60],['D',62],['E',64],['F',65],['G',67],['A',69]].map(([name,note]) => <option value={note} key={name}>{name}</option>)}</select></label><label>Scale <select value={scale} onChange={event => setScale(event.target.value as typeof scale)}><option value="minor">Minor</option><option value="major">Major</option><option value="pentatonic">Pentatonic</option></select></label></div><button onClick={makeMelody}>Generate scale melody</button><button onClick={addChordProgression}>Write 4-chord progression</button><label className="switch-line"><input type="checkbox" checked={arpEnabled} onChange={event => setArpEnabled(event.target.checked)}/> Arpeggiator on chord pads</label><small>Generated notes are constrained to the selected scale.</small></article><article className="tool-panel arrangement"><span>ARRANGEMENT</span><h3>Three-track session</h3>{[['Synth track', synthGain, setSynthGain], ['Drum track', drumGain, setDrumGain], ['Sampler track', engine.hasSample() ? 100 : 0, () => {}]].map(([name, value, setValue]: any) => <div className="track-row" key={name}><b>{name}</b><input aria-label={`${name} level`} type="range" min="0" max="100" value={value} onChange={event => setValue(+event.target.value)}/><span>{value}%</span></div>)}<p>Patterns loop across a 16-step arrangement. Track faders affect the real audio buses.</p></article></div>}
    {tab === 'sound' && <div className="deck-grid sound-grid"><article className="tool-panel"><span>SAMPLER + LOOP</span><h3>{sampleName}</h3><input ref={sampleInput} className="visually-hidden" type="file" accept="audio/*" onChange={event => event.target.files?.[0] && importSample(event.target.files[0])}/><button onClick={() => sampleInput.current?.click()}>Import audio sample</button><div className="dual-actions"><button disabled={!engine.hasSample()} onClick={() => engine.triggerSample(60)}>▶ C sample</button><button disabled={!engine.hasSample()} onClick={() => engine.triggerSample(67)}>▶ G sample</button></div><button className={recording ? 'recording' : ''} onClick={toggleRecording}>{recording ? '■ Stop studio recording' : '● Record studio → sampler'}</button><button className={micRecording ? 'recording' : ''} onClick={toggleMicRecording}>{micRecording ? '■ Stop microphone recording' : '● Capture microphone sample'}</button><button disabled={!engine.hasSample()} onClick={toggleLoop}>{looping ? '■ Stop 4-bar looper' : '↻ Loop sample every 4 bars'}</button><small>Samples pitch-map across C/G. The studio recorder and microphone recorder both load directly into the sampler.</small></article><article className="tool-panel"><span>EFFECTS + MASTER</span><h3>Live processing</h3><label>Drive <input type="range" min="0" max="1" step=".05" value={patch.drive} onChange={event => update('drive', +event.target.value)}/><b>{Math.round(patch.drive * 100)}%</b></label><label>Echo <input type="range" min="0" max="45" value={props.delay} onChange={event => props.setDelay(+event.target.value)}/><b>{props.delay}%</b></label><label>Synth level <input type="range" min="0" max="100" value={synthGain} onChange={event => { setSynthGain(+event.target.value); engine.setSynthGain(+event.target.value / 100); }}/><b>{synthGain}%</b></label><label>Drum level <input type="range" min="0" max="100" value={drumGain} onChange={event => { setDrumGain(+event.target.value); engine.setDrumGain(+event.target.value / 100); }}/><b>{drumGain}%</b></label><div className="drum-pads"><button onClick={() => engine.kick()}>Kick</button><button onClick={() => engine.snare()}>Snare</button><button onClick={() => engine.clap()}>Clap</button><button onClick={() => engine.hat()}>Hat</button></div><small>Drive and echo are live effects; independent busses form the base of the mixer rack. The drum pads audition more percussion sounds.</small></article><Analyser engine={engine}/></div>}
    {tab === 'files' && <div className="deck-grid files-grid"><article className="tool-panel"><span>OFFLINE EXPORT</span><h3>Render this loop locally</h3><button onClick={() => exportAudio('wav')}>Export WAV (44.1 kHz)</button><button onClick={() => exportAudio('mp3')}>Export MP3 (192 kbps)</button><button onClick={() => exportAudio('midi')}>Export MIDI</button><small>These formats are rendered on this device; no audio is uploaded.</small></article><article className="tool-panel"><span>MIDI + PERFORMANCE</span><h3>Bring in notes</h3><input ref={midiInput} className="visually-hidden" type="file" accept=".mid,.midi,audio/midi" onChange={event => event.target.files?.[0] && importMidi(event.target.files[0])}/><button onClick={() => midiInput.current?.click()}>Import MIDI file</button><button onClick={enableMidi}>Connect MIDI keyboard</button><small>Use your browser’s MIDI permission prompt to connect a hardware keyboard.</small></article><article className="tool-panel"><span>PLUGIN RACK</span><h3>Local modules</h3><div className="module-chips"><button>⇅ Synth</button><button>⇅ Sampler</button><button>⇅ Drive</button><button>⇅ Echo</button><button>⇅ Analyser</button></div><small>The local rack is ready for modular ordering. Cloud/VST/AU plugins require a native or hosted extension service.</small></article></div>}
    {tab === 'project' && <div className="deck-grid project-grid"><article className="tool-panel"><span>PRESETS</span><h3>Save your sound</h3><button onClick={saveCustomPreset}>Save custom patch</button><button onClick={() => toggleFavorite(patch.id)}>{favorites.includes(patch.id) ? '★ Remove from favorites' : '☆ Favorite current patch'}</button><p>{customPresets.length} custom · {favorites.length} favorite</p></article><article className="tool-panel"><span>SESSION HISTORY</span><h3>Version checkpoints</h3>{versions.length ? <ol className="version-list">{versions.slice(0, 5).map((version: any, index: number) => <li key={`${version.at}-${index}`}><b>{version.name}</b><span>{version.at}</span></li>)}</ol> : <p>Save the project to create a local checkpoint.</p>}<small>Browser saves preserve project history locally.</small></article><article className="tool-panel"><span>SHARE + THEME</span><h3>Local collaboration room</h3><button onClick={shareLocal}>Copy/share local project</button><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>Switch to {theme === 'dark' ? 'light' : 'dark'} theme</button><small>Open a second tab on this device to receive live local-room updates. Hosted sharing, accounts, and real-time remote collaboration need a backend.</small></article><article className="tool-panel"><span>AI MODULES</span><h3>Integration ready</h3><p>Text patch generation is local and active. Text-to-audio, reference analysis, stem separation, vocals, cloud sharing and billing need a model and server endpoint.</p><small>Those are intentionally marked as integrations rather than simulated results.</small></article></div>}
  </section>;
}

function Analyser({ engine }: { engine: SynthEngine }) {
  const canvas = useRef<HTMLCanvasElement | null>(null); const [level, setLevel] = useState(0);
  useEffect(() => { const element = canvas.current; if (!element) return; const context = element.getContext('2d'); if (!context) return; let frame = 0; const draw = () => { const width = element.clientWidth, height = element.clientHeight, ratio = Math.min(devicePixelRatio || 1, 2); if (element.width !== Math.round(width * ratio) || element.height !== Math.round(height * ratio)) { element.width = Math.round(width * ratio); element.height = Math.round(height * ratio); context.setTransform(ratio, 0, 0, ratio, 0, 0); } const data = engine.getSpectrum(); const nextLevel = engine.getLevel(); setLevel(current => Math.abs(current - nextLevel) > .015 ? nextLevel : current); context.fillStyle = '#0a120e'; context.fillRect(0, 0, width, height); if (data) { const bar = width / data.length * 1.65; for (let i = 0; i < data.length; i++) { const magnitude = (data[i] / 255) * height; context.fillStyle = i > data.length * .72 ? '#fbba69' : '#baff70'; context.fillRect(i * bar, height - magnitude, Math.max(1, bar - 1), magnitude); } } frame = requestAnimationFrame(draw); }; draw(); return () => cancelAnimationFrame(frame); }, [engine]);
  return <article className="tool-panel analyser"><span>SPECTRUM + LOUDNESS</span><h3>{Math.round(level * 100)}% master level</h3><canvas ref={canvas} role="img" aria-label="Live output frequency spectrum"/><div className="level-meter"><i style={{ width: `${Math.min(100, level * 100)}%` }}/></div><small>Green is safe headroom. Keep the meter below the final orange range.</small></article>;
}

function Oscilloscope({ engine, active }: { engine: SynthEngine; active: boolean }) {
  const canvas = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    const element = canvas.current; if (!element) return;
    const context = element.getContext('2d'); if (!context) return;
    let frame = 0;
    const resize = () => { const rect = element.getBoundingClientRect(); const ratio = Math.min(devicePixelRatio || 1, 2); element.width = Math.max(1, Math.round(rect.width * ratio)); element.height = Math.max(1, Math.round(rect.height * ratio)); context.setTransform(ratio, 0, 0, ratio, 0, 0); };
    const observer = new ResizeObserver(resize); observer.observe(element); resize();
    const draw = () => { const width = element.clientWidth, height = element.clientHeight; context.fillStyle = '#0b1210'; context.fillRect(0, 0, width, height); context.strokeStyle = '#294437'; context.lineWidth = 1; for (let x = 0; x < width; x += width / 12) { context.beginPath(); context.moveTo(x, 0); context.lineTo(x, height); context.stroke(); } for (let y = 0; y < height; y += height / 4) { context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke(); } const values = engine.getWaveform(); context.strokeStyle = '#caff72'; context.lineWidth = 2; context.shadowColor = '#8efb54'; context.shadowBlur = 10; context.beginPath(); if (values) { const slice = width / values.length; for (let i = 0; i < values.length; i++) { const y = (values[i] / 255) * height; if (i === 0) context.moveTo(0, y); else context.lineTo(i * slice, y); } } else { context.moveTo(0, height / 2); context.lineTo(width, height / 2); } context.stroke(); context.shadowBlur = 0; frame = requestAnimationFrame(draw); };
    draw(); return () => { cancelAnimationFrame(frame); observer.disconnect(); };
  }, [engine]);
  return <section className="scope" aria-label="Live audio oscilloscope"><div className="scope-header"><span>OUTPUT SCOPE</span><b>{active ? '● LIVE' : '○ STANDBY'}</b></div><canvas ref={canvas} role="img" aria-label="Live time-domain waveform of OmniSynth audio output"/><small>Real-time waveform · audio stays on your device</small></section>;
}

function Library({ presets, loadPreset, navigate, favorites = [], toggleFavorite = () => {} }: { presets: LibraryPatch[]; loadPreset: (patch: Patch) => void; navigate: (page: Page) => void; favorites?: string[]; toggleFavorite?: (id: string) => void }) { const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const categories = ['All', ...Array.from(new Set(presets.map(item => item.category)))]; const shown = presets.filter(item => (filter === 'All' || item.category === filter) && `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())); return <section className="content-page"><div className="page-intro"><p className="eyebrow">PATCH LIBRARY</p><h1>Start with a sound<br/><i>worth shaping.</i></h1><p>Every patch below is ready to load into the live synthesizer. Save your own sounds, tag favourites, then use them in Studio.</p><button className="ghost" onClick={() => navigate('studio')}>Open Studio →</button></div><input className="preset-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search patches or tags" aria-label="Search patches"/><div className="filter-row">{categories.map(category => <button onClick={() => setFilter(category)} className={filter === category ? 'filter-active' : ''} key={category}>{category}</button>)}</div><div className="preset-grid">{shown.map(item => <article className="preset-card" key={item.id}><button className="favorite" onClick={() => toggleFavorite(item.id)} aria-label={`Toggle ${item.name} favourite`}>{favorites.includes(item.id) ? '★' : '☆'}</button><div className="patch-icon">{item.waveform === 'sine' ? '∿' : item.waveform === 'square' ? '▥' : item.waveform === 'triangle' ? '△' : '╱'}</div><span>{item.category}</span><h2>{item.name}</h2><p>{item.description ?? 'Your locally saved sound.'}</p><dl><div><dt>Wave</dt><dd>{item.waveform}</dd></div><div><dt>Cutoff</dt><dd>{item.cutoff} Hz</dd></div></dl><button onClick={() => { loadPreset(item); navigate('studio'); }}>Load in Studio →</button></article>)}</div></section>; }

function Learn({ beginLesson, navigate }: { beginLesson: (patch: Patch, lesson: string) => void; navigate: (page: Page) => void }) { const [lesson, setLesson] = useState(0); const lessons = [{ title: 'First sound in 60 seconds', time: '3 min', patch: presetLibrary[0], steps: ['Open Studio and press Start making sound.', 'Hold a key on the on-screen keyboard.', 'Use Cutoff to make the sound darker or brighter.'] }, { title: 'Create your first beat', time: '5 min', patch: presetLibrary[2], steps: ['Load Deep Bass and press Play pattern.', 'Click cells in the drum lane to place kick hits.', 'Use Generate variation to create a new starting groove.'] }, { title: 'Make an atmospheric pad', time: '4 min', patch: presetLibrary[1], steps: ['Load Warm Pad into Studio.', 'Turn Attack and Release up for a slower shape.', 'Add a little Echo and hold a keyboard note.'] }]; const current = lessons[lesson]; return <section className="content-page learn-page"><div className="page-intro"><p className="eyebrow">LEARN OMNISYNTH</p><h1>Make your first<br/><i>complete idea.</i></h1><p>Short, hands-on lessons. Each lesson loads a usable sound and sends you to the exact part of Studio you need.</p></div><div className="lesson-layout"><aside className="lesson-list"><p>START HERE</p>{lessons.map((item, index) => <button key={item.title} className={lesson === index ? 'lesson-active' : ''} onClick={() => setLesson(index)}><small>LESSON 0{index + 1} · {item.time}</small>{item.title}</button>)}<button className="ghost" onClick={() => navigate('library')}>Browse patches →</button></aside><article className="lesson-card"><span>LESSON 0{lesson + 1} · {current.time}</span><h2>{current.title}</h2><p>Follow these steps, then use the live studio to experiment.</p><ol>{current.steps.map(item => <li key={item}>{item}</li>)}</ol><div className="lesson-actions"><button className="play" onClick={() => beginLesson(current.patch, current.title)}>Load lesson in Studio →</button><button className="ghost" onClick={() => setLesson((lesson + 1) % lessons.length)}>Next lesson</button></div></article></div></section>; }
